"""
Notification Service
Sends recommendations via email, calendar updates, or other channels
"""
import os
import base64
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import Dict, Optional
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError
from dotenv import load_dotenv

load_dotenv()

SCOPES = ['https://www.googleapis.com/auth/gmail.send']

class NotificationService:
    """Handles sending notifications via various channels"""
    
    def __init__(self):
        self.gmail_service = None
        self.notification_email = os.getenv('NOTIFICATION_EMAIL', '')
        self.notification_method = os.getenv('NOTIFICATION_METHOD', 'email').lower()
        self._setup_gmail()
    
    def _setup_gmail(self):
        """Setup Gmail service for email notifications"""
        try:
            creds = None
            if os.path.exists('token.json'):
                creds = Credentials.from_authorized_user_file('token.json', SCOPES)
            
            if not creds or not creds.valid:
                if creds and creds.expired and creds.refresh_token:
                    creds.refresh(Request())
                else:
                    # Gmail uses same token.json as Calendar
                    if os.path.exists('token.json'):
                        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
            
            if creds:
                self.gmail_service = build('gmail', 'v1', credentials=creds)
        except Exception as e:
            print(f"⚠️ Gmail setup warning: {e}")
            print("Email notifications may not work. Calendar updates will still work.")
    
    def send_recommendation(self, recommendation: str, event: Dict, 
                          constraints: Dict) -> bool:
        """
        Send recommendation via configured notification method
        
        Args:
            recommendation: Recommendation text
            event: Calendar event dictionary
            constraints: Extracted constraints
            
        Returns:
            True if sent successfully
        """
        if self.notification_method == 'email':
            return self.send_email(recommendation, event, constraints)
        elif self.notification_method == 'calendar':
            # Calendar updates handled separately
            return True
        else:
            print(f"Unknown notification method: {self.notification_method}")
            return False
    
    def send_email(self, recommendation: str, event: Dict, 
                   constraints: Dict) -> bool:
        """
        Send recommendation via email
        
        Args:
            recommendation: Recommendation text
            event: Calendar event dictionary
            constraints: Extracted constraints
            
        Returns:
            True if email sent successfully
        """
        if not self.gmail_service:
            print("❌ Gmail service not available")
            return False
        
        if not self.notification_email:
            print("⚠️ NOTIFICATION_EMAIL not set in .env")
            return False
        
        try:
            # Create email message
            subject = f"🍽️ Lunch Recommendation for {event.get('title', 'Your Meeting')}"
            
            body = f"""
Hi!

Here's your personalized lunch recommendation for today's meeting:

📅 Event: {event.get('title', 'Meeting')}
📍 Location: {event.get('location', 'N/A')}
⏰ Time: {constraints.get('time', 'N/A')}

{recommendation}

---
Generated by Lunza AI Agent
"""
            
            message = MIMEText(body)
            message['to'] = self.notification_email
            message['subject'] = subject
            
            # Encode message
            raw_message = base64.urlsafe_b64encode(message.as_bytes()).decode('utf-8')
            
            # Send message
            send_message = self.gmail_service.users().messages().send(
                userId='me',
                body={'raw': raw_message}
            ).execute()
            
            print(f"✅ Email sent successfully! Message ID: {send_message.get('id')}")
            return True
        
        except HttpError as error:
            print(f'❌ Error sending email: {error}')
            return False
    
    def format_recommendation_for_calendar(self, recommendation: str) -> str:
        """Format recommendation text for calendar event description"""
        return f"\n\n---\n🍽️ Lunza Recommendation:\n{recommendation}"

